In [1]:
import pandas as pd

In [3]:
CSV_PATH = "../data/draws_clean.csv"

## Replace the column names 
column_names = [
    "draw_number", "draw_date",
    "main_1", "main_2", "main_3", "main_4", "main_5" ,"main_6",
    "bouns", "powerball"
]

## header=0 means the original header row
## names=column_names means throw away those original header names and use mine instead
df = pd.read_csv(CSV_PATH, header=0, names=column_names)

## Shape gives us the number of rows and columns
print(df.shape)

## Head gives us the first 5 rows
df.head()

(1520, 10)

,draw_number,draw_date,main_1,main_2,main_3,main_4,main_5,main_6,bouns,powerball
0,2593,2026-06-10,2,7,12,17,21,37,35,6
1,2592,2026-06-06,3,22,29,37,39,40,13,1
2,2591,2026-06-03,1,4,9,11,13,36,24,9
3,2590,2026-05-30,8,10,29,35,36,39,3,3
4,2589,2026-05-27,6,17,19,21,27,32,28,10

In [7]:
df["draw_date"] = pd.to_datetime(df["draw_date"])

df = df.sort_values("draw_date").reset_index(drop=True)

print(df["draw_date"].dtype)
print("Oldest:", df["draw_date"].min())
print("Newest:", df["draw_date"].max())
df.head()

datetime64[us]
Oldest: 2008-01-05 00:00:00
Newest: 2026-06-10 00:00:00

,draw_number,draw_date,main_1,main_2,main_3,main_4,main_5,main_6,bouns,powerball
0,1074,2008-01-05,3,8,14,18,21,36,35,3
1,1075,2008-01-12,5,14,16,19,22,40,33,9
2,1076,2008-01-19,8,10,12,26,36,38,21,5
3,1077,2008-01-26,10,15,19,22,34,40,17,4
4,1078,2008-02-02,2,4,12,22,32,38,20,8